//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaktus.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vistavka_Caktusov
    {
        public int Id_Vistavka_Cactusov { get; set; }
        public int ID_Cactus { get; set; }
        public int ID_Vistavka { get; set; }
    
        public virtual Cactus Cactus { get; set; }
        public virtual Vistavka Vistavka { get; set; }
    }
}
